spring.application.name=app

spring.datasource.url=<Database URL>
spring.datasource.username=<Database username>
spring.datasource.password=<Database password>


# This should be set to 'update' only in development environments and none in production
spring.jpa.hibernate.ddl-auto=update

# Generated API Key for securing endpoints
API.KEY=your_generated_api_key_here
# Set the environment to 'development' or 'production' 
# If not set, defaults to 'production'
ENVIRONMENT=development 